### ISSUE TITLE
Format not supported for bookmark file

### ISSUE THREAD

**Issue by mattmartini** [quambene/bogrep#27]
When I try to import by bookmarks I get this error message: 
`Error: Format not supported for bookmark file`

I tried using a source that points to my Firefox Profile dir, My Chrome Bookmarks, a json file export of my Firefox bookmarks, and an export file of my Chrome bookmarks.  I deleted `settings.json` between each `bogrep config --source` command.  

I am running on Mac OS 11.7.10 (Big Sur).  The unit and integration tests all pass.  

How can I troubleshoot this issue further?

**Comment by quambene** [comment]
Thanks for your bug report.

Unfortunately, I couldn't test it on macOS so far (cf. https://github.com/quambene/bogrep#supported-operating-systems). Better macOS support is at the top of my list.

Currently, parts of the bookmark path are used to identify the format of the bookmarks file. On Ubuntu, the path looks like:

``` bash
# Firefox (snap package)
bogrep config --source ~/snap/firefox/common/.mozilla/firefox/<my_profile>/bookmarkbackups

# Firefox (apt package)
bogrep config --source ~/.mozilla/firefox/<my_profile>/bookmarkbackups

# Chrome
bogrep config --source ~/.config/google-chrome/Default/bookmarks
```

1. Could you let me know, how the path to the bookmark files for Firefox and Chrome look like on macOS? 

2. Could you also compare if the json format of the test files for Firefox and Chrome (see https://github.com/quambene/bogrep/tree/main/test_data/source) are similar to your bookmark files on macOs? 

Specifically, bogrep is looking for

- `"type": "text/x-moz-place"` for Firefox, and
- `"type": "url"` for Google Chrome.

in the bookmark files to identify bookmark objects.

3. Also, bookmarks for Firefox are compressed in `.jsonlz4 format on Ubuntu. Is it the same file extension on macOS?

A json export of the Firefox bookmarks wasn't tested yet. I will have a look on this.

**Comment by quambene** [comment]
Configuration for macOS (compare the README: https://github.com/quambene/bogrep):

- JSON file from Firefox, Chrome, or Chromium: `bogrep config --source /path/to/my/bookmarks.json`
- for Firefox: `bogrep config --source ~/Library/Application Support/Firefox/Profiles/<my_profile>/bookmarkbackups`
- for Chrome: `bogrep config --source ~/Library/Application Support/Google/Chrome/Default/Bookmarks`

Path to bookmark files may vary on the version of your OS. Bookmark files in HTML format are not supported yet.

**Comment by quambene** [comment]
Provided in v0.1.5

**Comment by mattmartini** [comment]
Thanks.  Both Firefox and Chrome bookmarks can be imported now.  On Fetch I am getting many `bogrep::cmd::fetch] Can't fetch website from <URL> operation timed out` errors.
