### ISSUE TITLE
GIF files fetched

### ISSUE THREAD

**Issue by mattmartini** [quambene/bogrep#29]
It seems that gif files are not excluded when fetching and are put into the cache.  
I had` http://sirocco.accuweather.com/sat_mosaic_640x480_public/rs/isarNE.gif ` in my bookmarks and when I did a bogrep search I got a `Match in bookmark` with that URL and binary junk.  The query I made happened to match some of the binary data.

**Comment by quambene** [comment]
Interesting, the link includes a `img` which should already be excluded. Will have a look at this!

**Comment by quambene** [comment]
Fixed in release v0.3.0: https://github.com/quambene/bogrep/blob/main/CHANGELOG.md#v030
