### ISSUE TITLE
Cache Mode ignored in settings

### ISSUE THREAD

**Issue by mattmartini** [quambene/bogrep#31]
With a clean import (and cache cleaned), using `bogrep import` & `bogrep fetch` the cache is filled with `.txt` files.  Again after cleaning, `bogrep import` & `bogrep fetch --mode markdown` fills the cache with `.md` files.  These are expected behaviors.

After cleaning again and editing `settings.json` setting `"cache_mode": "markdown",` and running `bogrep import` & `bogrep fetch` the cache is filled with `.txt` files.  The expected behavior should be to download `.md` files.

**Comment by quambene** [comment]
Fixed on main branch.

Now, `bogrep fetch` will use the cache mode configure in `settings.json`. On the other hand if `--mode` is specified (e.g. `bogrep fetch --mode markdown`), the cache mode provided in the `--mode` argument will be used instead.

**Comment by mattmartini** [comment]
My tests show that this is resolved.
