### ISSUE TITLE
Feature Request: Flag to Only list URLs

### ISSUE THREAD

**Issue by mattmartini** [quambene/bogrep#32]
Like grep or RipGrep there should be a `-l` flag to not show the text of the match, but only the URLs that have a match.   This can be aproximated with `bogrep <SEARCH> | grep 'Match in bookmark'`

**Comment by quambene** [comment]
Flag `-l` provided in v0.4.0. Please also note the new flag `-i` for case-insensitive search: https://github.com/quambene/bogrep#search.
